/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package screens;

import entities.Filme;
import entities.Sala;
import entities.Sessao;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import managers.GerenciaFilme;
import managers.GerenciaSala;
import managers.GerenciaSessao;

/**
 *
 * @author Andre
 */
public class ConsultaSessao extends javax.swing.JInternalFrame {

    GerenciaFilme gerFilme;
    GerenciaSala gerSala;
    GerenciaSessao gerSessao;
    Sala sala;
    Filme filme;
    String imagemDefault = "src/main/resources/images/cartaz.png";

    public ConsultaSessao(GerenciaFilme gerFilme, GerenciaSala gerSala, GerenciaSessao gerSessao) {
        initComponents();
        this.gerFilme = gerFilme;
        this.gerSala = gerSala;
        this.gerSessao = gerSessao;

        inicializaValores();
        listarSessoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        cmbFilme = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnImagem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbSala = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cmbSelecionarSessao = new javax.swing.JComboBox<>();
        spnData = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setTitle("Consultar Sessão");
        setMaximumSize(new java.awt.Dimension(515, 640));
        setMinimumSize(new java.awt.Dimension(515, 640));
        setPreferredSize(new java.awt.Dimension(515, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 614));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 614));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 614));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultar grande.png"))); // NOI18N
        jLabel1.setText("Consultar Sessão");

        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirme.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        cmbFilme.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbFilme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilmeItemStateChanged(evt);
            }
        });
        cmbFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilmeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Filme:");

        btnImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cartaz.png"))); // NOI18N
        btnImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImagem.setMaximumSize(new java.awt.Dimension(180, 260));
        btnImagem.setMinimumSize(new java.awt.Dimension(180, 260));
        btnImagem.setPreferredSize(new java.awt.Dimension(180, 260));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Horário:");

        cmbSala.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbSala.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSalaItemStateChanged(evt);
            }
        });
        cmbSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Sala:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Selecione uma sessão:");

        cmbSelecionarSessao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbSelecionarSessao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelecionarSessaoItemStateChanged(evt);
            }
        });
        cmbSelecionarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelecionarSessaoActionPerformed(evt);
            }
        });

        spnData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        spnData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1699135360296L), null, java.util.Calendar.DAY_OF_MONTH));
        spnData.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Estado da sala:");

        cmbEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em condição de uso", "Sem condição de uso", "Em manutenção" }));
        cmbEstado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelecionarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditar)
                                    .addComponent(btnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmar)
                            .addComponent(spnData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSelecionarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(spnData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnConfirmar))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (cmbEstado.getSelectedIndex() == 1 || cmbEstado.getSelectedIndex() == 2) {
            JOptionPane.showMessageDialog(this, "Não foi possível alterar pois a sala selecionada está indisponível!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Sessao sessao = new Sessao(gerFilme.consultar(cmbFilme.getSelectedIndex()), gerSala.consultar(cmbSala.getSelectedIndex()), spnData.getValue());
                gerSessao.editar(sessao, cmbSelecionarSessao.getSelectedIndex());
                JOptionPane.showMessageDialog(this, "Sessão alterada!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Não foi possível alterar. Revise os campos e tente novamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
            estadoInicial();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        estadoEditar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void cmbSelecionarSessaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelecionarSessaoItemStateChanged
        inicializaValores();
        preencheValores();
        estadoInicial();
    }//GEN-LAST:event_cmbSelecionarSessaoItemStateChanged

    private void cmbFilmeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilmeItemStateChanged
        try {
            filme = gerFilme.consultar(cmbFilme.getSelectedIndex());
            carregaImagem(filme.getCaminhoImagem());
        } catch (Exception e) {
            return;
        }
    }//GEN-LAST:event_cmbFilmeItemStateChanged

    private void cmbFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilmeActionPerformed

    private void cmbSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSalaActionPerformed

    private void cmbSalaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSalaItemStateChanged
        try {
            sala = gerSala.consultar(cmbSala.getSelectedIndex());
            cmbEstado.setSelectedIndex(sala.getStatus());
        } catch (Exception e) {
            return;
        }
    }//GEN-LAST:event_cmbSalaItemStateChanged

    private void cmbSelecionarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelecionarSessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelecionarSessaoActionPerformed

    private void carregaImagem(String caminhoImagem) {
        BufferedImage imagem;
        File file = new File(caminhoImagem);
        if (!caminhoImagem.equals(imagemDefault)) {
            try {
                imagem = ImageIO.read(file);
                btnImagem.setIcon(new ImageIcon(imagem.getScaledInstance(180, 260, 100)));
            } catch (IOException ex) {
                Logger.getLogger(ConsultaFilmes.class.getName()).log(Level.SEVERE, "Imagem não encontrada!", ex);
            }
        } else {
            try {
                imagem = ImageIO.read(file);
                btnImagem.setIcon(new ImageIcon(imagem));
            } catch (IOException ex) {
                Logger.getLogger(ConsultaFilmes.class.getName()).log(Level.SEVERE, "Imagem não encontrada!", ex);
            }
        }
    }

    private void preencheValores() {
        cmbFilme.setSelectedIndex(gerFilme.index(gerSessao.consultar(cmbSelecionarSessao.getSelectedIndex()).getFilme()));
        cmbSala.setSelectedIndex(gerSala.index(gerSessao.consultar(cmbSelecionarSessao.getSelectedIndex()).getSala()));
        spnData.setValue(gerSessao.consultar(cmbSelecionarSessao.getSelectedIndex()).getDataHora());
        filme = gerFilme.consultar(cmbFilme.getSelectedIndex());
        carregaImagem(filme.getCaminhoImagem());
    }

    private void estadoInicial() {
        cmbFilme.setEnabled(false);
        cmbSala.setEnabled(false);
        spnData.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnEditar.setEnabled(true);
    }

    private void estadoEditar() {
        cmbFilme.setEnabled(true);
        cmbSala.setEnabled(true);
        spnData.setEnabled(true);
        btnConfirmar.setEnabled(true);
        btnEditar.setEnabled(false);
    }

    private void listarSessoes() {
        cmbSelecionarSessao.removeAllItems();
        for (int i = 1; i <= gerSessao.relatorio().size(); i++) {
            cmbSelecionarSessao.addItem(String.valueOf(i));
        }
    }

    private void inicializaValores() {
        cmbFilme.removeAllItems();
        cmbSala.removeAllItems();
        gerFilme.relatorio().forEach(el -> cmbFilme.addItem(el.getTitulo()));
        gerSala.relatorio().forEach(el -> cmbSala.addItem(String.valueOf(el.getNumSala())));
        cmbSala.setSelectedIndex(0);
        cmbFilme.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnImagem;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFilme;
    private javax.swing.JComboBox<String> cmbSala;
    private javax.swing.JComboBox<String> cmbSelecionarSessao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner spnData;
    // End of variables declaration//GEN-END:variables
}
