/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package screens;

import entities.Filme;
import entities.Venda;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import entities.CarrinhoDeCompras;
import managers.GerenciaCarrinhoDeCompras;
import managers.GerenciaIngresso;
import managers.GerenciaProduto;
import managers.GerenciaSessao;

/**
 *
 * @author Andre
 */
public class Vender extends javax.swing.JInternalFrame {

    GerenciaSessao gerSessao;
    GerenciaProduto gerProduto;
    String imagemDefault = "src/main/resources/images/cartaz.png";
    GerenciaCarrinhoDeCompras gerCarrinho;
    CarrinhoDeCompras carrinhoDeCompras = new CarrinhoDeCompras();

    private ArrayList<Integer> ingressos = new ArrayList<>();

    /**
     * Creates new form Vender
     *
     * @param gerSessao
     * @param gerProduto
     * @param gerCarrinho
     */
    public Vender(GerenciaSessao gerSessao, GerenciaProduto gerProduto, GerenciaCarrinhoDeCompras gerCarrinho) {
        initComponents();
        tableCarrinhoDeCompras.setModel(carrinhoDeCompras);
        this.gerCarrinho = gerCarrinho;
        this.gerSessao = gerSessao;
        this.gerProduto = gerProduto;
        cmbSessao.removeAllItems();
        listarSessoes();
        preencherProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoIngresso = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cmbSessao = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiretor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbClassificacao = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopse = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        cmbPoltrona = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JSpinner();
        txtDuracao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnAdicionarPoltrona = new javax.swing.JButton();
        btnRemoveCliente = new javax.swing.JButton();
        cmbProdutos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCarrinhoDeCompras = new javax.swing.JTable();
        btnCartaz = new javax.swing.JButton();
        btnImagemProduto = new javax.swing.JButton();
        radioNaoPg = new javax.swing.JRadioButton();
        radioMeia = new javax.swing.JRadioButton();
        radioInteira = new javax.swing.JRadioButton();
        btnListarPoltronas = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Vendas");
        setMaximumSize(new java.awt.Dimension(1098, 648));
        setMinimumSize(new java.awt.Dimension(1098, 648));
        setNormalBounds(new java.awt.Rectangle(0, 0, 1098, 648));
        setPreferredSize(new java.awt.Dimension(1098, 648));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1086, 604));
        jPanel1.setMinimumSize(new java.awt.Dimension(1086, 604));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrinho-grande.png"))); // NOI18N
        jLabel1.setText("Carrinho de Compras");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Sala:");

        cmbSessao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbSessao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSessaoItemStateChanged(evt);
            }
        });
        cmbSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSessaoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Sessão:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Data:");

        txtTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTitulo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Título:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Filme:");

        txtSala.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSala.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Diretor:");

        txtDiretor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiretor.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Ano:");

        txtAno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAno.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Classificação:");

        cmbClassificacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10 Anos", "12 Anos", "14 Anos", "16 Anos", "18 Anos" }));
        cmbClassificacao.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Gênero:");

        txtGenero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGenero.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Duração:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Sinopse:");

        txtSinopse.setColumns(20);
        txtSinopse.setRows(5);
        txtSinopse.setEnabled(false);
        jScrollPane1.setViewportView(txtSinopse);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel13.setText("Produtos");

        btnAddProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAddProduto.setText("Adicionar");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setText("Valor total:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setText("R$");

        txtValorTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtValorTotal.setEnabled(false);

        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirme.png"))); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelarVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });

        cmbPoltrona.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbPoltrona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPoltronaItemStateChanged(evt);
            }
        });
        cmbPoltrona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPoltronaActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1699212988951L), null, null, java.util.Calendar.DAY_OF_MONTH));
        txtData.setEnabled(false);

        txtDuracao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDuracao.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setText("Selecionar Poltrona");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAdicionarPoltrona.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdicionarPoltrona.setText("Adicionar");
        btnAdicionarPoltrona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPoltronaActionPerformed(evt);
            }
        });

        btnRemoveCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRemoveCliente.setText("Remover Item");
        btnRemoveCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveClienteActionPerformed(evt);
            }
        });

        cmbProdutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProdutosItemStateChanged(evt);
            }
        });
        cmbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdutosActionPerformed(evt);
            }
        });

        tableCarrinhoDeCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableCarrinhoDeCompras.setMaximumSize(new java.awt.Dimension(300, 80));
        tableCarrinhoDeCompras.setMinimumSize(new java.awt.Dimension(300, 80));
        jScrollPane2.setViewportView(tableCarrinhoDeCompras);

        btnCartaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cartaz.png"))); // NOI18N
        btnCartaz.setMaximumSize(new java.awt.Dimension(180, 260));
        btnCartaz.setMinimumSize(new java.awt.Dimension(180, 260));
        btnCartaz.setPreferredSize(new java.awt.Dimension(180, 260));

        btnImagemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refrigerante.png"))); // NOI18N
        btnImagemProduto.setMaximumSize(new java.awt.Dimension(180, 260));
        btnImagemProduto.setMinimumSize(new java.awt.Dimension(180, 260));
        btnImagemProduto.setPreferredSize(new java.awt.Dimension(180, 260));

        grpTipoIngresso.add(radioNaoPg);
        radioNaoPg.setText("Não Pagante");

        grpTipoIngresso.add(radioMeia);
        radioMeia.setText("Meia");

        grpTipoIngresso.add(radioInteira);
        radioInteira.setText("Inteira");

        btnListarPoltronas.setText("Listar Poltronas");
        btnListarPoltronas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPoltronasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSala)
                                            .addComponent(cmbSessao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCartaz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdicionarPoltrona))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(radioNaoPg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioMeia)
                                        .addGap(12, 12, 12)
                                        .addComponent(radioInteira))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnListarPoltronas)))
                        .addGap(21, 21, 21)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAddProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnCancelarVenda)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnConfirmar))
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRemoveCliente)
                                .addGap(4, 4, 4)))))
                .addGap(22, 22, 22))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel6)
                                    .addGap(28, 28, 28)
                                    .addComponent(btnCartaz, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarPoltronas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioInteira)
                                    .addComponent(radioMeia)
                                    .addComponent(radioNaoPg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionarPoltrona))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveCliente)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelarVenda)
                                    .addComponent(btnConfirmar))
                                .addGap(52, 52, 52))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)
                        .addGap(28, 28, 28)
                        .addComponent(btnImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddProduto)
                        .addGap(85, 85, 85))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPoltronaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPoltronaItemStateChanged

    }//GEN-LAST:event_cmbPoltronaItemStateChanged

    private void cmbSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSessaoActionPerformed

    private void cmbSessaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSessaoItemStateChanged
        preencheCampos();
    }//GEN-LAST:event_cmbSessaoItemStateChanged

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        // TODO add your handling code here:
        try {
            Venda venda = new Venda(
                    gerProduto.consultar(cmbProdutos.getSelectedIndex()).getNome(),
                    gerProduto.consultar(cmbProdutos.getSelectedIndex()).getPreco());
            carrinhoDeCompras.addRow(venda);
            updateValorTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnAdicionarPoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPoltronaActionPerformed

        try {
            if (radioInteira.isSelected() || radioNaoPg.isSelected() || radioMeia.isSelected()) {
                float tipo = 0;
                if (radioInteira.isSelected()) {
                    tipo = 30;
                } else if (radioMeia.isSelected()) {
                    tipo = 15;
                } else if (radioNaoPg.isSelected()) {
                    tipo = 0;
                }
                Venda venda = new Venda("Ingresso", tipo);
                carrinhoDeCompras.addRow(venda);
                updateValorTotal();
                ingressos.add(Integer.valueOf(cmbPoltrona.getSelectedItem().toString()));
                cmbPoltrona.removeItemAt(cmbPoltrona.getSelectedIndex());
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um tipo de ingresso!");
            }
            preencherPoltronas();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnAdicionarPoltronaActionPerformed

    private void cmbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProdutosActionPerformed

    private void btnRemoveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveClienteActionPerformed
        if (tableCarrinhoDeCompras.getSelectedRow() != -1) {
            carrinhoDeCompras.removeRow(tableCarrinhoDeCompras.getSelectedRow());
            updateValorTotal();
        }
    }//GEN-LAST:event_btnRemoveClienteActionPerformed

    private void cmbPoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPoltronaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPoltronaActionPerformed

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    private void btnListarPoltronasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPoltronasActionPerformed
        preencherPoltronas();
    }//GEN-LAST:event_btnListarPoltronasActionPerformed

    private void cmbProdutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProdutosItemStateChanged
        carregaImagem(gerProduto.consultar(cmbProdutos.getSelectedIndex()).getCaminhoImagem(), btnImagemProduto, 151, 260);
    }//GEN-LAST:event_cmbProdutosItemStateChanged

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            if (!txtValorTotal.getText().isEmpty()) {
                ingressos.forEach(el -> gerSessao.consultar(cmbSessao.getSelectedIndex()).reservaPoltrona(el));
                JOptionPane.showMessageDialog(this, "Venda realizada!");
                this.setClosed(true);
                gerCarrinho.adicionar(carrinhoDeCompras);
            } else {
                JOptionPane.showMessageDialog(this, "Carrinho vazio!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void listarSessoes() {
        cmbSessao.removeAllItems();
        for (int i = 1; i <= gerSessao.relatorio().size(); i++) {
            cmbSessao.addItem(String.valueOf(i));
        }
    }

    private void preencherPoltronas() {
        try {
            cmbPoltrona.removeAllItems();
            gerSessao.consultar(cmbSessao.getSelectedIndex()).getPoltronas().forEach(
                    el -> {
                        if (el != 0) {
                            cmbPoltrona.addItem(String.valueOf(el));
                        }
                    }
            );
        } catch (Exception e) {
            return;
        }
    }

    private void preencherProdutos() {
        try {
            cmbProdutos.removeAllItems();
            gerProduto.relatorio().forEach(el -> cmbProdutos.addItem(el.getNome()));
        } catch (Exception e) {
            return;
        }
    }

    private void preencheCampos() {
        Filme filme = gerSessao.consultar(cmbSessao.getSelectedIndex()).getFilme();
        txtAno.setText(String.valueOf(filme.getAno()));
        txtData.setValue(gerSessao.consultar(cmbSessao.getSelectedIndex()).getDataHora());
        txtDiretor.setText(filme.getDiretor());
        txtDuracao.setText(String.valueOf(filme.getDuracao()));
        txtGenero.setText(filme.getGenero());
        txtSala.setText(String.valueOf(gerSessao.consultar(cmbSessao.getSelectedIndex()).getSala().getNumSala()));
        txtSinopse.setText(filme.getSinopse());
        txtTitulo.setText(filme.getTitulo());
        carregaImagem(filme.getCaminhoImagem(), btnCartaz, 180, 260);
    }

    private void updateValorTotal() {
        txtValorTotal.setText(String.valueOf(carrinhoDeCompras.calculaValorTotal()));
    }

    private void carregaImagem(String caminhoImagem, JButton botao, int w, int h) {
        BufferedImage imagem;
        File file = new File(caminhoImagem);
        if (!caminhoImagem.equals(imagemDefault)) {
            try {
                imagem = ImageIO.read(file);
                botao.setIcon(new ImageIcon(imagem.getScaledInstance(w, h, 100)));
            } catch (IOException ex) {
                Logger.getLogger(ConsultaFilmes.class.getName()).log(Level.SEVERE, "Imagem não encontrada!", ex);
            }
        } else {
            try {
                imagem = ImageIO.read(file);
                botao.setIcon(new ImageIcon(imagem));
            } catch (IOException ex) {
                Logger.getLogger(ConsultaFilmes.class.getName()).log(Level.SEVERE, "Imagem não encontrada!", ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAdicionarPoltrona;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnCartaz;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnImagemProduto;
    private javax.swing.JButton btnListarPoltronas;
    private javax.swing.JButton btnRemoveCliente;
    private javax.swing.JComboBox<String> cmbClassificacao;
    private javax.swing.JComboBox<String> cmbPoltrona;
    private javax.swing.JComboBox<String> cmbProdutos;
    private javax.swing.JComboBox<String> cmbSessao;
    private javax.swing.ButtonGroup grpTipoIngresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton radioInteira;
    private javax.swing.JRadioButton radioMeia;
    private javax.swing.JRadioButton radioNaoPg;
    private javax.swing.JTable tableCarrinhoDeCompras;
    private javax.swing.JTextField txtAno;
    private javax.swing.JSpinner txtData;
    private javax.swing.JTextField txtDiretor;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextArea txtSinopse;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
